# Generated by Django 4.2.4 on 2024-07-09 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0002_alter_tag_options_task_uuid_alter_tag_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='title',
            new_name='name',
        ),
    ]
